table Data
	lineageTag: c3cfa453-0408-4140-8087-48cca7f6e3d9

	column Column1
		dataType: string
		lineageTag: 1c2807a7-d329-4f44-8c56-85003e8792ef
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 33231e44-0330-4550-88f4-20e6960e4222
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column 'Sample Data - Power BI'
		dataType: string
		lineageTag: 36be530c-bb0d-4f0d-93fe-ea2d2ad7b5f3
		summarizeBy: none
		sourceColumn: Sample Data - Power BI

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: aad4e509-4003-4b3f-a36e-2f7f7700ac3b
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: 6f029df2-0356-4b76-a920-f3fb8245c288
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: b1ec46ea-d457-4690-8ca4-d46327652c0a
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: f72081a0-c059-4998-8bf1-b28cbe4118ff
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: dd36c302-72c1-4902-8613-59092244cc2c
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: 8d33be1d-3ea7-48bd-8ce7-567f235d917f
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	partition Data = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\amanp\Downloads\pb-sales-data-blank.xlsx"), null, true),
				    Data_Sheet = Source{[Item="Data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Data_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Column1", type any}, {"Column2", type any}, {"Sample Data - Power BI", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

