table sales
	lineageTag: 0b24f0c6-2ab4-4eab-8d9b-a7973cfe3dc9

	column 'Sales Person'
		dataType: string
		lineageTag: 156c35ab-bae3-44a2-8ed8-db6683865171
		summarizeBy: none
		sourceColumn: Sales Person

		annotation SummarizationSetBy = Automatic

	column Geography
		dataType: string
		lineageTag: a04459d4-8dff-4bea-ba36-8095e5d0a5ad
		summarizeBy: none
		sourceColumn: Geography

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 0b4b85f4-4c3d-4ed1-bc3f-eafe427a7faf
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8d6b668b-3c4e-494f-bb54-6d8d482291f0
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 547145e7-67c4-4239-be73-62f09cf2c467
			defaultHierarchy: LocalDateTable_33414e71-cf1e-4f2c-939a-f61eb167c900.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Amount
		dataType: int64
		formatString: 0
		lineageTag: 528b8c46-ca65-42c7-b8d1-2f308a91c970
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column Customers
		dataType: int64
		formatString: 0
		lineageTag: 9cdc68b3-af56-4cfc-8d3a-462bd4383e93
		summarizeBy: sum
		sourceColumn: Customers

		annotation SummarizationSetBy = Automatic

	column Boxes
		dataType: int64
		formatString: 0
		lineageTag: 7210057c-54fb-4b1b-849b-2a72aca730dc
		summarizeBy: sum
		sourceColumn: Boxes

		annotation SummarizationSetBy = Automatic

	partition sales = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\amanp\Downloads\pb-sales-data-blank.xlsx"), null, true),
				    sales_Table = Source{[Item="sales",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(sales_Table,{{"Sales Person", type text}, {"Geography", type text}, {"Product", type text}, {"Date", type date}, {"Amount", Int64.Type}, {"Customers", Int64.Type}, {"Boxes", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

